### ISSUE TITLE
It doesn't remove the line ending like a regular cut, just blanks the line.

### ISSUE THREAD

**Issue by fadec** [vscode-plugins/Copy-Gather-Paste#1] opened 2020-04-27 02:02 UTC
It doesn't remove the line ending like a regular cut, just blanks the line. This makes it necessary to move the cursor to cut multiple adjacent lines.

**Comment by serge1** [comment] 2020-04-28 20:21
I could not reproduce the issue according to the description. Would you please explain it more? Please describe exact scenario and cursor positions. Thank you

**Comment by serge1** [comment] 2020-06-10 21:28
I could not reproduce the issue according to the description. Would you please explain it more? Please describe exact scenario and cursor positions. Thank you

**Comment by serge1** [comment] 2020-07-19 16:48
Due to the lack of the feedback, I am closing the issue. Please reopen if the problem persists.

**Closed as completed by serge1** 2020-07-19 16:48 UTC
